version: '3.4'

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      POSTGRES_DB: "binnosoft"
      POSTGRES_USER: "jeanfernandes"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: unless-stopped

  s3ninja:
    image: kcomlabs/s3ninja
    ports:
      - "9444:9444"
    container_name: s3

networks:
  default:
    ipam:
      config:
        - subnet: "172.80.0.0/16"