version: '3.4'

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "binnosoft"
      POSTGRES_USER: "jeanfernandes"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - "/var/lib/postgresql/data/"
    container_name: pgbinno

  s3ninja:
    image: kcomlabs/s3ninja
    ports:
      - "9444:9444"
    container_name: s3