server:
  port: 8080

spring:
  profiles:
    active: local
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: schema_history

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 3

    platform: postgres
    url: jdbc:postgresql://localhost:5432/binnosoft
    username: jeanfernandes
    password: admin
    driverClassName: org.postgresql.Driver

jwt:
  expiration: 36000000
  secret: SECRETO

aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  host: http://localhost:9444/s3
  s3:
    bucket: binno-agro
    region: us-east-1

mail:
  domain: central.binnoapp.com
  api_key: no-havis
