server:
  port: 8080

spring:
  #pra resolver o problema do openui na versao 2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: schema_history
    enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:db_test;MODE=POSTGRESQL

  h2:
    console:
      enabled: true
      path: /h2

jwt:
  expiration: 36000000

aws:
  access_key_id: AKIAIOSFODNN7EXAMPLE
  secret_access_key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  host: http://localhost:9444/s3
  s3:
    bucket: binno-agro
    region: us-east-1

mail:
  domain: central.binnoapp.com
  api_key: nao_tem