server:
  port: ${PORT}

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    locations: classpath:db/migration
    table: schema_history

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 3

    platform: postgres
    url: jdbc:postgresql://${PG_HOST}:5432/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
    driverClassName: org.postgresql.Driver

jwt:
  expiration: 3600000
  secret: ${JWT_KEY}

aws:
  access_key_id: ${AWS_KEY}
  secret_access_key: ${AWS_SECRET}
  host:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}

mail:
  domain: central.binnoapp.com
  api_key: ${API_KEY_MAIL}
